site_name: UniLink Docs
site_url: https://unilink-docs.pages.dev

# Pages
nav:
  - Overview: index.md
  - Installation:
      - Backend Setup Guide: installation/backend.md
      - Frontend Setup Guide: installation/frontend.md
  - API Documentations:
      - User: api/user.md
      - University: api/university.md
  # - Installation: installation.md
  # - Usage: usage.md
  # - Contributing: contributing.md
  # - License: license.md

# Repository
repo_name: ehsan18t/unilink
repo_url: https://github.com/ehsan18t/unilink

# Footer
copyright: Copyright &copy; 2023 Team Showstopper

extra_css:
  - assets/stylesheets/extra.css

# Theme
theme:
  name: material
  favicon: assets/images/logo.svg
  logo: assets/images/logo.svg
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - announce.dismiss
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

extra:
  generator: false # Hide made with MKDocs
  annotate:
    json: [.s2]
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ehsan18t
    - icon: fontawesome/brands/discord
      link: https://discord.com
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com
    - icon: fontawesome/brands/twitter
      link: https://twitter.com
    - icon: fontawesome/brands/facebook
      link: https://facebook.com

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: false
      user: ehsan18t
      repo: unilink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.critic
